- hosts: all
  connection: chroot
  roles:
    - systemd
    - cryptsetup
    - irqbalance
    - lxc
    - openssh-server
    - rdnssd
    - rsyslog-client
    - socat
    - role: wireguard
      wireguard_dkms: true
  vars:
    restart_services: false
